create table level (id varchar(255) generated by default as identity, code varchar(255), name varchar(255), status varchar(255), id_school varchar(255) not null, primary key (id));
create table school (id varchar(255) generated by default as identity, address varchar(255), created_at varchar(255), deleted_at varchar(255), inep integer, name varchar(255), number varchar(255), updated_at varchar(255), primary key (id));
create table school_level (school_id varchar(255) not null, level_id varchar(255) not null);
alter table school_level add constraint UK_j7ig9otiff9xgm7axv0l90fl9 unique (level_id);
alter table level add constraint FK47btc27fpy9s90l3o6cfpmkm1 foreign key (id_school) references school on delete cascade;
alter table school_level add constraint FK3cbeuwvn264y79yg1l1yo6qd9 foreign key (level_id) references level;
alter table school_level add constraint FKd3806odbpc82e46q551vn72y9 foreign key (school_id) references school;
